// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"gopkg.in/volatiletech/null.v6"
)

// Boat is an object representing the database table.
type Boat struct {
	ID          int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	TimeTrialID null.Int  `boil:"time_trial_id" json:"time_trial_id,omitempty" toml:"time_trial_id" yaml:"time_trial_id,omitempty"`
	BowMarker   null.Int  `boil:"bow_marker" json:"bow_marker,omitempty" toml:"bow_marker" yaml:"bow_marker,omitempty"`
	Name        string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	Start       null.Int  `boil:"start" json:"start,omitempty" toml:"start" yaml:"start,omitempty"`
	End         null.Int  `boil:"end" json:"end,omitempty" toml:"end" yaml:"end,omitempty"`
	Time        null.Int  `boil:"time" json:"time,omitempty" toml:"time" yaml:"time,omitempty"`
	CreatedAt   time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt   time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *boatR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L boatL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BoatColumns = struct {
	ID          string
	TimeTrialID string
	BowMarker   string
	Name        string
	Start       string
	End         string
	Time        string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "id",
	TimeTrialID: "time_trial_id",
	BowMarker:   "bow_marker",
	Name:        "name",
	Start:       "start",
	End:         "end",
	Time:        "time",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

// boatR is where relationships are stored.
type boatR struct {
	TimeTrial *TimeTrial
}

// boatL is where Load methods for each relationship are stored.
type boatL struct{}

var (
	boatColumns               = []string{"id", "time_trial_id", "bow_marker", "name", "start", "end", "time", "created_at", "updated_at"}
	boatColumnsWithoutDefault = []string{"time_trial_id", "bow_marker", "name", "start", "end", "time", "created_at", "updated_at"}
	boatColumnsWithDefault    = []string{"id"}
	boatPrimaryKeyColumns     = []string{"id"}
)

type (
	// BoatSlice is an alias for a slice of pointers to Boat.
	// This should generally be used opposed to []Boat.
	BoatSlice []*Boat
	// BoatHook is the signature for custom Boat hook methods
	BoatHook func(boil.Executor, *Boat) error

	boatQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	boatType                 = reflect.TypeOf(&Boat{})
	boatMapping              = queries.MakeStructMapping(boatType)
	boatPrimaryKeyMapping, _ = queries.BindMapping(boatType, boatMapping, boatPrimaryKeyColumns)
	boatInsertCacheMut       sync.RWMutex
	boatInsertCache          = make(map[string]insertCache)
	boatUpdateCacheMut       sync.RWMutex
	boatUpdateCache          = make(map[string]updateCache)
	boatUpsertCacheMut       sync.RWMutex
	boatUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var boatBeforeInsertHooks []BoatHook
var boatBeforeUpdateHooks []BoatHook
var boatBeforeDeleteHooks []BoatHook
var boatBeforeUpsertHooks []BoatHook

var boatAfterInsertHooks []BoatHook
var boatAfterSelectHooks []BoatHook
var boatAfterUpdateHooks []BoatHook
var boatAfterDeleteHooks []BoatHook
var boatAfterUpsertHooks []BoatHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Boat) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range boatBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Boat) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range boatBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Boat) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range boatBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Boat) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range boatBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Boat) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range boatAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Boat) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range boatAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Boat) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range boatAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Boat) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range boatAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Boat) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range boatAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBoatHook registers your hook function for all future operations.
func AddBoatHook(hookPoint boil.HookPoint, boatHook BoatHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		boatBeforeInsertHooks = append(boatBeforeInsertHooks, boatHook)
	case boil.BeforeUpdateHook:
		boatBeforeUpdateHooks = append(boatBeforeUpdateHooks, boatHook)
	case boil.BeforeDeleteHook:
		boatBeforeDeleteHooks = append(boatBeforeDeleteHooks, boatHook)
	case boil.BeforeUpsertHook:
		boatBeforeUpsertHooks = append(boatBeforeUpsertHooks, boatHook)
	case boil.AfterInsertHook:
		boatAfterInsertHooks = append(boatAfterInsertHooks, boatHook)
	case boil.AfterSelectHook:
		boatAfterSelectHooks = append(boatAfterSelectHooks, boatHook)
	case boil.AfterUpdateHook:
		boatAfterUpdateHooks = append(boatAfterUpdateHooks, boatHook)
	case boil.AfterDeleteHook:
		boatAfterDeleteHooks = append(boatAfterDeleteHooks, boatHook)
	case boil.AfterUpsertHook:
		boatAfterUpsertHooks = append(boatAfterUpsertHooks, boatHook)
	}
}

// OneP returns a single boat record from the query, and panics on error.
func (q boatQuery) OneP() *Boat {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single boat record from the query.
func (q boatQuery) One() (*Boat, error) {
	o := &Boat{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for boat")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Boat records from the query, and panics on error.
func (q boatQuery) AllP() BoatSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Boat records from the query.
func (q boatQuery) All() (BoatSlice, error) {
	var o []*Boat

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Boat slice")
	}

	if len(boatAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Boat records in the query, and panics on error.
func (q boatQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Boat records in the query.
func (q boatQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count boat rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q boatQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q boatQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if boat exists")
	}

	return count > 0, nil
}

// TimeTrialG pointed to by the foreign key.
func (o *Boat) TimeTrialG(mods ...qm.QueryMod) timeTrialQuery {
	return o.TimeTrial(boil.GetDB(), mods...)
}

// TimeTrial pointed to by the foreign key.
func (o *Boat) TimeTrial(exec boil.Executor, mods ...qm.QueryMod) timeTrialQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.TimeTrialID),
	}

	queryMods = append(queryMods, mods...)

	query := TimeTrials(exec, queryMods...)
	queries.SetFrom(query.Query, "\"time_trial\"")

	return query
} // LoadTimeTrial allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (boatL) LoadTimeTrial(e boil.Executor, singular bool, maybeBoat interface{}) error {
	var slice []*Boat
	var object *Boat

	count := 1
	if singular {
		object = maybeBoat.(*Boat)
	} else {
		slice = *maybeBoat.(*[]*Boat)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &boatR{}
		}
		args[0] = object.TimeTrialID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &boatR{}
			}
			args[i] = obj.TimeTrialID
		}
	}

	query := fmt.Sprintf(
		"select * from \"time_trial\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load TimeTrial")
	}
	defer results.Close()

	var resultSlice []*TimeTrial
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice TimeTrial")
	}

	if len(boatAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.TimeTrial = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TimeTrialID.Int == foreign.ID {
				local.R.TimeTrial = foreign
				break
			}
		}
	}

	return nil
}

// SetTimeTrialG of the boat to the related item.
// Sets o.R.TimeTrial to related.
// Adds o to related.R.Boats.
// Uses the global database handle.
func (o *Boat) SetTimeTrialG(insert bool, related *TimeTrial) error {
	return o.SetTimeTrial(boil.GetDB(), insert, related)
}

// SetTimeTrialP of the boat to the related item.
// Sets o.R.TimeTrial to related.
// Adds o to related.R.Boats.
// Panics on error.
func (o *Boat) SetTimeTrialP(exec boil.Executor, insert bool, related *TimeTrial) {
	if err := o.SetTimeTrial(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetTimeTrialGP of the boat to the related item.
// Sets o.R.TimeTrial to related.
// Adds o to related.R.Boats.
// Uses the global database handle and panics on error.
func (o *Boat) SetTimeTrialGP(insert bool, related *TimeTrial) {
	if err := o.SetTimeTrial(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetTimeTrial of the boat to the related item.
// Sets o.R.TimeTrial to related.
// Adds o to related.R.Boats.
func (o *Boat) SetTimeTrial(exec boil.Executor, insert bool, related *TimeTrial) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"boat\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"time_trial_id"}),
		strmangle.WhereClause("\"", "\"", 2, boatPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TimeTrialID.Int = related.ID
	o.TimeTrialID.Valid = true

	if o.R == nil {
		o.R = &boatR{
			TimeTrial: related,
		}
	} else {
		o.R.TimeTrial = related
	}

	if related.R == nil {
		related.R = &timeTrialR{
			Boats: BoatSlice{o},
		}
	} else {
		related.R.Boats = append(related.R.Boats, o)
	}

	return nil
}

// RemoveTimeTrialG relationship.
// Sets o.R.TimeTrial to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle.
func (o *Boat) RemoveTimeTrialG(related *TimeTrial) error {
	return o.RemoveTimeTrial(boil.GetDB(), related)
}

// RemoveTimeTrialP relationship.
// Sets o.R.TimeTrial to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Panics on error.
func (o *Boat) RemoveTimeTrialP(exec boil.Executor, related *TimeTrial) {
	if err := o.RemoveTimeTrial(exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveTimeTrialGP relationship.
// Sets o.R.TimeTrial to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle and panics on error.
func (o *Boat) RemoveTimeTrialGP(related *TimeTrial) {
	if err := o.RemoveTimeTrial(boil.GetDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveTimeTrial relationship.
// Sets o.R.TimeTrial to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *Boat) RemoveTimeTrial(exec boil.Executor, related *TimeTrial) error {
	var err error

	o.TimeTrialID.Valid = false
	if err = o.Update(exec, "time_trial_id"); err != nil {
		o.TimeTrialID.Valid = true
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.TimeTrial = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Boats {
		if o.TimeTrialID.Int != ri.TimeTrialID.Int {
			continue
		}

		ln := len(related.R.Boats)
		if ln > 1 && i < ln-1 {
			related.R.Boats[i] = related.R.Boats[ln-1]
		}
		related.R.Boats = related.R.Boats[:ln-1]
		break
	}
	return nil
}

// BoatsG retrieves all records.
func BoatsG(mods ...qm.QueryMod) boatQuery {
	return Boats(boil.GetDB(), mods...)
}

// Boats retrieves all the records using an executor.
func Boats(exec boil.Executor, mods ...qm.QueryMod) boatQuery {
	mods = append(mods, qm.From("\"boat\""))
	return boatQuery{NewQuery(exec, mods...)}
}

// FindBoatG retrieves a single record by ID.
func FindBoatG(id int, selectCols ...string) (*Boat, error) {
	return FindBoat(boil.GetDB(), id, selectCols...)
}

// FindBoatGP retrieves a single record by ID, and panics on error.
func FindBoatGP(id int, selectCols ...string) *Boat {
	retobj, err := FindBoat(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindBoat retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBoat(exec boil.Executor, id int, selectCols ...string) (*Boat, error) {
	boatObj := &Boat{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"boat\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(boatObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from boat")
	}

	return boatObj, nil
}

// FindBoatP retrieves a single record by ID with an executor, and panics on error.
func FindBoatP(exec boil.Executor, id int, selectCols ...string) *Boat {
	retobj, err := FindBoat(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Boat) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Boat) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Boat) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Boat) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no boat provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(boatColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	boatInsertCacheMut.RLock()
	cache, cached := boatInsertCache[key]
	boatInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			boatColumns,
			boatColumnsWithDefault,
			boatColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(boatType, boatMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(boatType, boatMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"boat\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"boat\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into boat")
	}

	if !cached {
		boatInsertCacheMut.Lock()
		boatInsertCache[key] = cache
		boatInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Boat record. See Update for
// whitelist behavior description.
func (o *Boat) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Boat record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Boat) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Boat, and panics on error.
// See Update for whitelist behavior description.
func (o *Boat) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Boat.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Boat) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	boatUpdateCacheMut.RLock()
	cache, cached := boatUpdateCache[key]
	boatUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			boatColumns,
			boatPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update boat, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"boat\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, boatPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(boatType, boatMapping, append(wl, boatPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update boat row")
	}

	if !cached {
		boatUpdateCacheMut.Lock()
		boatUpdateCache[key] = cache
		boatUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q boatQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q boatQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for boat")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o BoatSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o BoatSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o BoatSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BoatSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), boatPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"boat\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, boatPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in boat slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Boat) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Boat) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Boat) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Boat) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no boat provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(boatColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	boatUpsertCacheMut.RLock()
	cache, cached := boatUpsertCache[key]
	boatUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			boatColumns,
			boatColumnsWithDefault,
			boatColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			boatColumns,
			boatPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert boat, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(boatPrimaryKeyColumns))
			copy(conflict, boatPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"boat\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(boatType, boatMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(boatType, boatMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert boat")
	}

	if !cached {
		boatUpsertCacheMut.Lock()
		boatUpsertCache[key] = cache
		boatUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Boat record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Boat) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Boat record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Boat) DeleteG() error {
	if o == nil {
		return errors.New("models: no Boat provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Boat record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Boat) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Boat record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Boat) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Boat provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), boatPrimaryKeyMapping)
	sql := "DELETE FROM \"boat\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from boat")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q boatQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q boatQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no boatQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from boat")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o BoatSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o BoatSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Boat slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o BoatSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BoatSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Boat slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(boatBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), boatPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"boat\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, boatPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from boat slice")
	}

	if len(boatAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Boat) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Boat) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Boat) ReloadG() error {
	if o == nil {
		return errors.New("models: no Boat provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Boat) Reload(exec boil.Executor) error {
	ret, err := FindBoat(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *BoatSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *BoatSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BoatSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty BoatSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BoatSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	boats := BoatSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), boatPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"boat\".* FROM \"boat\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, boatPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&boats)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BoatSlice")
	}

	*o = boats

	return nil
}

// BoatExists checks if the Boat row exists.
func BoatExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"boat\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if boat exists")
	}

	return exists, nil
}

// BoatExistsG checks if the Boat row exists.
func BoatExistsG(id int) (bool, error) {
	return BoatExists(boil.GetDB(), id)
}

// BoatExistsGP checks if the Boat row exists. Panics on error.
func BoatExistsGP(id int) bool {
	e, err := BoatExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// BoatExistsP checks if the Boat row exists. Panics on error.
func BoatExistsP(exec boil.Executor, id int) bool {
	e, err := BoatExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
