// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Group            string
	Boat             string
	GooseDBVersion   string
	Organization     string
	OrganizationAuth string
	Rental           string
	RentalRowers     string
	Rower            string
	RowerGroup       string
	Shell            string
	TimeTrial        string
}{
	Group:            "Group",
	Boat:             "boat",
	GooseDBVersion:   "goose_db_version",
	Organization:     "organization",
	OrganizationAuth: "organization_auth",
	Rental:           "rental",
	RentalRowers:     "rental_rowers",
	Rower:            "rower",
	RowerGroup:       "rower_group",
	Shell:            "shell",
	TimeTrial:        "time_trial",
}
