// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"gopkg.in/volatiletech/null.v6"
)

// Timetrial is an object representing the database table.
type Timetrial struct {
	ID           int          `boil:"id" json:"id" toml:"id" yaml:"id"`
	Date         time.Time    `boil:"date" json:"date" toml:"date" yaml:"date"`
	StartTime    null.Time    `boil:"start_time" json:"start_time,omitempty" toml:"start_time" yaml:"start_time,omitempty"`
	EndTime      null.Time    `boil:"end_time" json:"end_time,omitempty" toml:"end_time" yaml:"end_time,omitempty"`
	TimingStatus null.Int     `boil:"timing_status" json:"timing_status,omitempty" toml:"timing_status" yaml:"timing_status,omitempty"`
	Timers       null.Int     `boil:"timers" json:"timers,omitempty" toml:"timers" yaml:"timers,omitempty"`
	Distnace     null.Float64 `boil:"distnace" json:"distnace,omitempty" toml:"distnace" yaml:"distnace,omitempty"`
	CreatedAt    null.Time    `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt    time.Time    `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *timetrialR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L timetrialL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TimetrialColumns = struct {
	ID           string
	Date         string
	StartTime    string
	EndTime      string
	TimingStatus string
	Timers       string
	Distnace     string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "id",
	Date:         "date",
	StartTime:    "start_time",
	EndTime:      "end_time",
	TimingStatus: "timing_status",
	Timers:       "timers",
	Distnace:     "distnace",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

// timetrialR is where relationships are stored.
type timetrialR struct {
	TimeTrialBoats BoatSlice
}

// timetrialL is where Load methods for each relationship are stored.
type timetrialL struct{}

var (
	timetrialColumns               = []string{"id", "date", "start_time", "end_time", "timing_status", "timers", "distnace", "created_at", "updated_at"}
	timetrialColumnsWithoutDefault = []string{"date", "start_time", "end_time", "timing_status", "timers", "distnace", "created_at", "updated_at"}
	timetrialColumnsWithDefault    = []string{"id"}
	timetrialPrimaryKeyColumns     = []string{"id"}
)

type (
	// TimetrialSlice is an alias for a slice of pointers to Timetrial.
	// This should generally be used opposed to []Timetrial.
	TimetrialSlice []*Timetrial
	// TimetrialHook is the signature for custom Timetrial hook methods
	TimetrialHook func(boil.Executor, *Timetrial) error

	timetrialQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	timetrialType                 = reflect.TypeOf(&Timetrial{})
	timetrialMapping              = queries.MakeStructMapping(timetrialType)
	timetrialPrimaryKeyMapping, _ = queries.BindMapping(timetrialType, timetrialMapping, timetrialPrimaryKeyColumns)
	timetrialInsertCacheMut       sync.RWMutex
	timetrialInsertCache          = make(map[string]insertCache)
	timetrialUpdateCacheMut       sync.RWMutex
	timetrialUpdateCache          = make(map[string]updateCache)
	timetrialUpsertCacheMut       sync.RWMutex
	timetrialUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var timetrialBeforeInsertHooks []TimetrialHook
var timetrialBeforeUpdateHooks []TimetrialHook
var timetrialBeforeDeleteHooks []TimetrialHook
var timetrialBeforeUpsertHooks []TimetrialHook

var timetrialAfterInsertHooks []TimetrialHook
var timetrialAfterSelectHooks []TimetrialHook
var timetrialAfterUpdateHooks []TimetrialHook
var timetrialAfterDeleteHooks []TimetrialHook
var timetrialAfterUpsertHooks []TimetrialHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Timetrial) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range timetrialBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Timetrial) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range timetrialBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Timetrial) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range timetrialBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Timetrial) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range timetrialBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Timetrial) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range timetrialAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Timetrial) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range timetrialAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Timetrial) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range timetrialAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Timetrial) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range timetrialAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Timetrial) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range timetrialAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTimetrialHook registers your hook function for all future operations.
func AddTimetrialHook(hookPoint boil.HookPoint, timetrialHook TimetrialHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		timetrialBeforeInsertHooks = append(timetrialBeforeInsertHooks, timetrialHook)
	case boil.BeforeUpdateHook:
		timetrialBeforeUpdateHooks = append(timetrialBeforeUpdateHooks, timetrialHook)
	case boil.BeforeDeleteHook:
		timetrialBeforeDeleteHooks = append(timetrialBeforeDeleteHooks, timetrialHook)
	case boil.BeforeUpsertHook:
		timetrialBeforeUpsertHooks = append(timetrialBeforeUpsertHooks, timetrialHook)
	case boil.AfterInsertHook:
		timetrialAfterInsertHooks = append(timetrialAfterInsertHooks, timetrialHook)
	case boil.AfterSelectHook:
		timetrialAfterSelectHooks = append(timetrialAfterSelectHooks, timetrialHook)
	case boil.AfterUpdateHook:
		timetrialAfterUpdateHooks = append(timetrialAfterUpdateHooks, timetrialHook)
	case boil.AfterDeleteHook:
		timetrialAfterDeleteHooks = append(timetrialAfterDeleteHooks, timetrialHook)
	case boil.AfterUpsertHook:
		timetrialAfterUpsertHooks = append(timetrialAfterUpsertHooks, timetrialHook)
	}
}

// OneP returns a single timetrial record from the query, and panics on error.
func (q timetrialQuery) OneP() *Timetrial {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single timetrial record from the query.
func (q timetrialQuery) One() (*Timetrial, error) {
	o := &Timetrial{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for timetrial")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Timetrial records from the query, and panics on error.
func (q timetrialQuery) AllP() TimetrialSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Timetrial records from the query.
func (q timetrialQuery) All() (TimetrialSlice, error) {
	var o []*Timetrial

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Timetrial slice")
	}

	if len(timetrialAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Timetrial records in the query, and panics on error.
func (q timetrialQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Timetrial records in the query.
func (q timetrialQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count timetrial rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q timetrialQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q timetrialQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if timetrial exists")
	}

	return count > 0, nil
}

// TimeTrialBoatsG retrieves all the boat's boat via time_trial_id column.
func (o *Timetrial) TimeTrialBoatsG(mods ...qm.QueryMod) boatQuery {
	return o.TimeTrialBoats(boil.GetDB(), mods...)
}

// TimeTrialBoats retrieves all the boat's boat with an executor via time_trial_id column.
func (o *Timetrial) TimeTrialBoats(exec boil.Executor, mods ...qm.QueryMod) boatQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"boat\".\"time_trial_id\"=?", o.ID),
	)

	query := Boats(exec, queryMods...)
	queries.SetFrom(query.Query, "\"boat\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"boat\".*"})
	}

	return query
}

// LoadTimeTrialBoats allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (timetrialL) LoadTimeTrialBoats(e boil.Executor, singular bool, maybeTimetrial interface{}) error {
	var slice []*Timetrial
	var object *Timetrial

	count := 1
	if singular {
		object = maybeTimetrial.(*Timetrial)
	} else {
		slice = *maybeTimetrial.(*[]*Timetrial)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &timetrialR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &timetrialR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"boat\" where \"time_trial_id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load boat")
	}
	defer results.Close()

	var resultSlice []*Boat
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice boat")
	}

	if len(boatAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.TimeTrialBoats = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.TimeTrialID.Int {
				local.R.TimeTrialBoats = append(local.R.TimeTrialBoats, foreign)
				break
			}
		}
	}

	return nil
}

// AddTimeTrialBoatsG adds the given related objects to the existing relationships
// of the timetrial, optionally inserting them as new records.
// Appends related to o.R.TimeTrialBoats.
// Sets related.R.TimeTrial appropriately.
// Uses the global database handle.
func (o *Timetrial) AddTimeTrialBoatsG(insert bool, related ...*Boat) error {
	return o.AddTimeTrialBoats(boil.GetDB(), insert, related...)
}

// AddTimeTrialBoatsP adds the given related objects to the existing relationships
// of the timetrial, optionally inserting them as new records.
// Appends related to o.R.TimeTrialBoats.
// Sets related.R.TimeTrial appropriately.
// Panics on error.
func (o *Timetrial) AddTimeTrialBoatsP(exec boil.Executor, insert bool, related ...*Boat) {
	if err := o.AddTimeTrialBoats(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTimeTrialBoatsGP adds the given related objects to the existing relationships
// of the timetrial, optionally inserting them as new records.
// Appends related to o.R.TimeTrialBoats.
// Sets related.R.TimeTrial appropriately.
// Uses the global database handle and panics on error.
func (o *Timetrial) AddTimeTrialBoatsGP(insert bool, related ...*Boat) {
	if err := o.AddTimeTrialBoats(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTimeTrialBoats adds the given related objects to the existing relationships
// of the timetrial, optionally inserting them as new records.
// Appends related to o.R.TimeTrialBoats.
// Sets related.R.TimeTrial appropriately.
func (o *Timetrial) AddTimeTrialBoats(exec boil.Executor, insert bool, related ...*Boat) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.TimeTrialID.Int = o.ID
			rel.TimeTrialID.Valid = true
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"boat\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"time_trial_id"}),
				strmangle.WhereClause("\"", "\"", 2, boatPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.TimeTrialID.Int = o.ID
			rel.TimeTrialID.Valid = true
		}
	}

	if o.R == nil {
		o.R = &timetrialR{
			TimeTrialBoats: related,
		}
	} else {
		o.R.TimeTrialBoats = append(o.R.TimeTrialBoats, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &boatR{
				TimeTrial: o,
			}
		} else {
			rel.R.TimeTrial = o
		}
	}
	return nil
}

// SetTimeTrialBoatsG removes all previously related items of the
// timetrial replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.TimeTrial's TimeTrialBoats accordingly.
// Replaces o.R.TimeTrialBoats with related.
// Sets related.R.TimeTrial's TimeTrialBoats accordingly.
// Uses the global database handle.
func (o *Timetrial) SetTimeTrialBoatsG(insert bool, related ...*Boat) error {
	return o.SetTimeTrialBoats(boil.GetDB(), insert, related...)
}

// SetTimeTrialBoatsP removes all previously related items of the
// timetrial replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.TimeTrial's TimeTrialBoats accordingly.
// Replaces o.R.TimeTrialBoats with related.
// Sets related.R.TimeTrial's TimeTrialBoats accordingly.
// Panics on error.
func (o *Timetrial) SetTimeTrialBoatsP(exec boil.Executor, insert bool, related ...*Boat) {
	if err := o.SetTimeTrialBoats(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetTimeTrialBoatsGP removes all previously related items of the
// timetrial replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.TimeTrial's TimeTrialBoats accordingly.
// Replaces o.R.TimeTrialBoats with related.
// Sets related.R.TimeTrial's TimeTrialBoats accordingly.
// Uses the global database handle and panics on error.
func (o *Timetrial) SetTimeTrialBoatsGP(insert bool, related ...*Boat) {
	if err := o.SetTimeTrialBoats(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetTimeTrialBoats removes all previously related items of the
// timetrial replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.TimeTrial's TimeTrialBoats accordingly.
// Replaces o.R.TimeTrialBoats with related.
// Sets related.R.TimeTrial's TimeTrialBoats accordingly.
func (o *Timetrial) SetTimeTrialBoats(exec boil.Executor, insert bool, related ...*Boat) error {
	query := "update \"boat\" set \"time_trial_id\" = null where \"time_trial_id\" = $1"
	values := []interface{}{o.ID}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err := exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.TimeTrialBoats {
			rel.TimeTrialID.Valid = false
			if rel.R == nil {
				continue
			}

			rel.R.TimeTrial = nil
		}

		o.R.TimeTrialBoats = nil
	}
	return o.AddTimeTrialBoats(exec, insert, related...)
}

// RemoveTimeTrialBoatsG relationships from objects passed in.
// Removes related items from R.TimeTrialBoats (uses pointer comparison, removal does not keep order)
// Sets related.R.TimeTrial.
// Uses the global database handle.
func (o *Timetrial) RemoveTimeTrialBoatsG(related ...*Boat) error {
	return o.RemoveTimeTrialBoats(boil.GetDB(), related...)
}

// RemoveTimeTrialBoatsP relationships from objects passed in.
// Removes related items from R.TimeTrialBoats (uses pointer comparison, removal does not keep order)
// Sets related.R.TimeTrial.
// Panics on error.
func (o *Timetrial) RemoveTimeTrialBoatsP(exec boil.Executor, related ...*Boat) {
	if err := o.RemoveTimeTrialBoats(exec, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveTimeTrialBoatsGP relationships from objects passed in.
// Removes related items from R.TimeTrialBoats (uses pointer comparison, removal does not keep order)
// Sets related.R.TimeTrial.
// Uses the global database handle and panics on error.
func (o *Timetrial) RemoveTimeTrialBoatsGP(related ...*Boat) {
	if err := o.RemoveTimeTrialBoats(boil.GetDB(), related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveTimeTrialBoats relationships from objects passed in.
// Removes related items from R.TimeTrialBoats (uses pointer comparison, removal does not keep order)
// Sets related.R.TimeTrial.
func (o *Timetrial) RemoveTimeTrialBoats(exec boil.Executor, related ...*Boat) error {
	var err error
	for _, rel := range related {
		rel.TimeTrialID.Valid = false
		if rel.R != nil {
			rel.R.TimeTrial = nil
		}
		if err = rel.Update(exec, "time_trial_id"); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.TimeTrialBoats {
			if rel != ri {
				continue
			}

			ln := len(o.R.TimeTrialBoats)
			if ln > 1 && i < ln-1 {
				o.R.TimeTrialBoats[i] = o.R.TimeTrialBoats[ln-1]
			}
			o.R.TimeTrialBoats = o.R.TimeTrialBoats[:ln-1]
			break
		}
	}

	return nil
}

// TimetrialsG retrieves all records.
func TimetrialsG(mods ...qm.QueryMod) timetrialQuery {
	return Timetrials(boil.GetDB(), mods...)
}

// Timetrials retrieves all the records using an executor.
func Timetrials(exec boil.Executor, mods ...qm.QueryMod) timetrialQuery {
	mods = append(mods, qm.From("\"timetrial\""))
	return timetrialQuery{NewQuery(exec, mods...)}
}

// FindTimetrialG retrieves a single record by ID.
func FindTimetrialG(id int, selectCols ...string) (*Timetrial, error) {
	return FindTimetrial(boil.GetDB(), id, selectCols...)
}

// FindTimetrialGP retrieves a single record by ID, and panics on error.
func FindTimetrialGP(id int, selectCols ...string) *Timetrial {
	retobj, err := FindTimetrial(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindTimetrial retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTimetrial(exec boil.Executor, id int, selectCols ...string) (*Timetrial, error) {
	timetrialObj := &Timetrial{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"timetrial\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(timetrialObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from timetrial")
	}

	return timetrialObj, nil
}

// FindTimetrialP retrieves a single record by ID with an executor, and panics on error.
func FindTimetrialP(exec boil.Executor, id int, selectCols ...string) *Timetrial {
	retobj, err := FindTimetrial(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Timetrial) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Timetrial) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Timetrial) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Timetrial) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no timetrial provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(timetrialColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	timetrialInsertCacheMut.RLock()
	cache, cached := timetrialInsertCache[key]
	timetrialInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			timetrialColumns,
			timetrialColumnsWithDefault,
			timetrialColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(timetrialType, timetrialMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(timetrialType, timetrialMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"timetrial\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"timetrial\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into timetrial")
	}

	if !cached {
		timetrialInsertCacheMut.Lock()
		timetrialInsertCache[key] = cache
		timetrialInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Timetrial record. See Update for
// whitelist behavior description.
func (o *Timetrial) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Timetrial record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Timetrial) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Timetrial, and panics on error.
// See Update for whitelist behavior description.
func (o *Timetrial) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Timetrial.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Timetrial) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	timetrialUpdateCacheMut.RLock()
	cache, cached := timetrialUpdateCache[key]
	timetrialUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			timetrialColumns,
			timetrialPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update timetrial, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"timetrial\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, timetrialPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(timetrialType, timetrialMapping, append(wl, timetrialPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update timetrial row")
	}

	if !cached {
		timetrialUpdateCacheMut.Lock()
		timetrialUpdateCache[key] = cache
		timetrialUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q timetrialQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q timetrialQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for timetrial")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o TimetrialSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o TimetrialSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o TimetrialSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TimetrialSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), timetrialPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"timetrial\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, timetrialPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in timetrial slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Timetrial) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Timetrial) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Timetrial) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Timetrial) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no timetrial provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(timetrialColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	timetrialUpsertCacheMut.RLock()
	cache, cached := timetrialUpsertCache[key]
	timetrialUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			timetrialColumns,
			timetrialColumnsWithDefault,
			timetrialColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			timetrialColumns,
			timetrialPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert timetrial, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(timetrialPrimaryKeyColumns))
			copy(conflict, timetrialPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"timetrial\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(timetrialType, timetrialMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(timetrialType, timetrialMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert timetrial")
	}

	if !cached {
		timetrialUpsertCacheMut.Lock()
		timetrialUpsertCache[key] = cache
		timetrialUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Timetrial record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Timetrial) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Timetrial record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Timetrial) DeleteG() error {
	if o == nil {
		return errors.New("models: no Timetrial provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Timetrial record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Timetrial) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Timetrial record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Timetrial) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Timetrial provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), timetrialPrimaryKeyMapping)
	sql := "DELETE FROM \"timetrial\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from timetrial")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q timetrialQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q timetrialQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no timetrialQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from timetrial")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o TimetrialSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o TimetrialSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Timetrial slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o TimetrialSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TimetrialSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Timetrial slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(timetrialBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), timetrialPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"timetrial\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, timetrialPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from timetrial slice")
	}

	if len(timetrialAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Timetrial) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Timetrial) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Timetrial) ReloadG() error {
	if o == nil {
		return errors.New("models: no Timetrial provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Timetrial) Reload(exec boil.Executor) error {
	ret, err := FindTimetrial(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *TimetrialSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *TimetrialSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TimetrialSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty TimetrialSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TimetrialSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	timetrials := TimetrialSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), timetrialPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"timetrial\".* FROM \"timetrial\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, timetrialPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&timetrials)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in TimetrialSlice")
	}

	*o = timetrials

	return nil
}

// TimetrialExists checks if the Timetrial row exists.
func TimetrialExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"timetrial\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if timetrial exists")
	}

	return exists, nil
}

// TimetrialExistsG checks if the Timetrial row exists.
func TimetrialExistsG(id int) (bool, error) {
	return TimetrialExists(boil.GetDB(), id)
}

// TimetrialExistsGP checks if the Timetrial row exists. Panics on error.
func TimetrialExistsGP(id int) bool {
	e, err := TimetrialExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// TimetrialExistsP checks if the Timetrial row exists. Panics on error.
func TimetrialExistsP(exec boil.Executor, id int) bool {
	e, err := TimetrialExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
